%% PLEASE Note: this code was generated by codex. 
%because its only plotting, I have not added comments to it. If you want me to add comments, please let me know.

function plotTemperatureMeshes(plotData,IntFactor,Decomp_method,solverType)
%PLOTTEMPERATUREMESHES Plot temperature contours for multiple mesh sizes.

numMeshes = numel(plotData);

if numMeshes == 0
    return
end

Tmin = inf;
Tmax = -inf;

for k = 1:numMeshes
    Tmin = min(Tmin,min(plotData(k).Tsol(:)));
    Tmax = max(Tmax,max(plotData(k).Tsol(:)));
end

for k = 1:numMeshes
    figure
    contourf(plotData(k).XC,plotData(k).YC,plotData(k).Tsol,20,'LineColor','none')
    caxis([Tmin Tmax])
    colorbar
    xlabel('X')
    ylabel('Y')
    title(sprintf(['Temperature Contours | m = %d, n = %d\n' ...
        'Interpolation: %s | Decomposition: %s | Solver: %s'], ...
        plotData(k).m,plotData(k).n, ...
        char(IntFactor),char(Decomp_method),upper(char(solverType))))
end

end
