function [aE,aW,aN,aS,aC,bC] = applyAnalyticalBoundaryConditions( ...
    aE,aW,aN,aS,aC,bC, ...
    Gamma, ...
    XC,YC, ...
    Xe,Ye,Xw,Yw,Xn,Yn,Xs,Ys, ...
    Se,Sw,Sn,Ss, ...
    Nx,Ny)
%APPLYANALYTICALBOUNDARYCONDITIONS Apply the benchmark BCs on Grid_test.

bc.west.type = 'dirichlet';
bc.west.value = 400.0;

bc.east.type = 'dirichlet';
bc.east.value = 300.0;

bc.south.type = 'neumann';
bc.south.value = 0.0;

bc.north.type = 'neumann';
bc.north.value = 0.0;

[aE,aW,aN,aS,aC,bC] = applyBoundaryConditions( ...
    aE,aW,aN,aS,aC,bC, ...
    Gamma, ...
    XC,YC, ...
    Xe,Ye,Xw,Yw,Xn,Yn,Xs,Ys, ...
    Se,Sw,Sn,Ss, ...
    Nx,Ny,bc);

end
